export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT= "SET_INGREDIENT";
export const FETCH_INGREDIENT_FAILED= "FETCH_INGREDIENT_FAILED";

export const PURSHASE_ORDER_START = 'PURSHASE_ORDER_START'
export const PURSHASE_ORDER_SUCCESS = 'PURSHASE_ORDER_SUCCESS'
export const PURSHASE_ORDER_FAILED = 'PURSHASE_ORDER_FAILED'
export const PURSHASE_ORDER_INIT = 'PURSHASE_ORDER_INIT'

export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL'


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';



export const AUTH_REDIRCT = 'AUTH_REDIRCT';